-- SGI Metalúrgica: Script de Estructura de Datos

CREATE TABLE clientes (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL,
    email text,
    telefono text,
    direccion text,
    lista_precio_asignada text
);

CREATE TABLE productos (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL,
    descripcion text,
    tipo text,
    stock_actual int4 DEFAULT 0,
    precio_minorista numeric,
    precio_mayorista numeric,
    precio_especial numeric
);

CREATE TABLE pedidos (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cliente_id int8 REFERENCES clientes(id),
    fecha_creacion timestamptz DEFAULT now(),
    estado text,
    total numeric,
    fecha timestamptz
);

CREATE TABLE detalle_pedido (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    pedido_id int8 REFERENCES pedidos(id),
    producto_id int8 REFERENCES productos(id),
    cantidad int4,
    precio_unitario numeric
);

CREATE TABLE movimientos_stock (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    producto_id int8 REFERENCES productos(id),
    tipo_movimiento text, 
    cantidad int4,
    fecha timestamptz DEFAULT now(),
    usuario_id uuid REFERENCES auth.users(id)
);